{% set name = "nodify" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nodify-{{ version }}.tar.gz
  sha256: 2e522c4ac1e3415b4e75f1b2395244e7a36a4447babcd440c6c610851fa2ea68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9

test:
  imports:
    - nodify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pfebrer/nodify
  summary: Supercharge your functional application with a powerful node system.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pfebrer
